name: bind9
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: clearlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run bind9 build script
        run: ./bind9.sh clear-linux-os x86-64-v3 9.21.2 "${{ secrets.SECRET_ID }}" "${{ secrets.SECRET_KEY }}" "${{ secrets.TOKEN }}"
